# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telegram_comms.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14telegram_comms.proto\"*\n\x13NotificationMessage\x12\x13\n\x0bmessage_str\x18\x01 \x01(\t\"\x1e\n\x0bServerReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32J\n\x0etelegram_comms\x12\x38\n\x10sendNotification\x12\x14.NotificationMessage\x1a\x0c.ServerReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telegram_comms_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTIFICATIONMESSAGE._serialized_start=24
  _NOTIFICATIONMESSAGE._serialized_end=66
  _SERVERREPLY._serialized_start=68
  _SERVERREPLY._serialized_end=98
  _TELEGRAM_COMMS._serialized_start=100
  _TELEGRAM_COMMS._serialized_end=174
# @@protoc_insertion_point(module_scope)
